# Generated by Django 4.1.3 on 2022-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
